spring:
  application:
    name: systemProvide
server:
#服务注册中心端口号
  port: 9011
eureka:
  instance:
#服务注册中心实例的主机名
    hostname: localhost
  client:
  #是否向服务注册中心注册自己
    register-with-eureka: false 
  #是否检索服务  
    fetch-registry: false
#服务注册中心的配置内容，指定服务注册中心的位置
#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/